package tokens_test

import (
	"context"
	"testing"
	"time"

	"github.com/golang-jwt/jwt/v5"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/rubensantoniorosa2704/auth-service/internal/adapters/tokens"
)

const (
	validSecret = "12345678901234567890123456789012" // exactly 32 bytes
	validIssuer = "test-service"
)

// newJWTService returns a valid JWTService for use in tests.
func newJWTService(t *testing.T) *tokens.JWTService {
	t.Helper()

	svc, err := tokens.NewJWTService(validSecret, validIssuer)
	require.NoError(t, err, "newJWTService: unexpected error creating service")

	return svc
}

// =====================
// NewJWTService tests
// =====================

func TestNewJWTService(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name        string
		secret      string
		issuer      string
		wantErr     bool
		errContains string
	}{
		{
			name:   "valid secret with exactly 32 bytes",
			secret: "12345678901234567890123456789012",
			issuer: validIssuer,
		},
		{
			name:   "valid secret longer than 32 bytes",
			secret: "this-is-a-very-long-secret-with-more-than-32-bytes-for-extra-security",
			issuer: validIssuer,
		},
		{
			name:        "empty secret",
			secret:      "",
			issuer:      validIssuer,
			wantErr:     true,
			errContains: "secret cannot be empty",
		},
		{
			name:        "secret with 9 bytes — too short",
			secret:      "short-key",
			issuer:      validIssuer,
			wantErr:     true,
			errContains: "secret must be at least 32 bytes long",
		},
		{
			name:        "secret with 31 bytes — one byte below minimum",
			secret:      "almost-valid-but-one-byte-shor",
			issuer:      validIssuer,
			wantErr:     true,
			errContains: "secret must be at least 32 bytes long",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			svc, err := tokens.NewJWTService(tt.secret, tt.issuer)

			if tt.wantErr {
				require.Error(t, err)
				assert.ErrorContains(t, err, tt.errContains)
				assert.Nil(t, svc, "service must be nil on error")
				return
			}

			require.NoError(t, err)
			assert.NotNil(t, svc)
		})
	}
}

// =====================
// Generate tests
// =====================

func TestJWTService_Generate(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		userID  string
		wantErr bool
	}{
		{
			name:   "generates token for valid user ID",
			userID: "user-123",
		},
		{
			name:   "generates token for UUID",
			userID: "550e8400-e29b-41d4-a716-446655440000",
		},
		{
			name:   "accepts empty user ID",
			userID: "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			svc := newJWTService(t)
			token, err := svc.Generate(context.Background(), tt.userID)

			if tt.wantErr {
				require.Error(t, err)
				assert.Empty(t, token)
				return
			}

			require.NoError(t, err)
			assert.NotEmpty(t, token, "token must not be empty")
		})
	}
}

// =====================
// Validate tests
// =====================

func TestJWTService_Validate(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		buildToken func(t *testing.T, svc *tokens.JWTService) string
		wantUserID string
		wantErr    bool
	}{
		{
			name: "validates token generated by the same service",
			buildToken: func(t *testing.T, svc *tokens.JWTService) string {
				t.Helper()
				token, err := svc.Generate(context.Background(), "user-abc")
				require.NoError(t, err)
				return token
			},
			wantUserID: "user-abc",
		},
		{
			name:       "fails with empty token",
			buildToken: func(t *testing.T, _ *tokens.JWTService) string { return "" },
			wantErr:    true,
		},
		{
			name:       "fails with random string",
			buildToken: func(t *testing.T, _ *tokens.JWTService) string { return "not-a-jwt-at-all" },
			wantErr:    true,
		},
		{
			name:       "fails with malformed JWT",
			buildToken: func(t *testing.T, _ *tokens.JWTService) string { return "a.b.c" },
			wantErr:    true,
		},
		{
			name: "fails with token signed by a different secret",
			buildToken: func(t *testing.T, _ *tokens.JWTService) string {
				t.Helper()
				otherSecret := "outrosecretcompletatmente-diferente-32b"
				otherSvc, err := tokens.NewJWTService(otherSecret, validIssuer)
				require.NoError(t, err)
				token, err := otherSvc.Generate(context.Background(), "user-xyz")
				require.NoError(t, err)
				return token
			},
			wantErr: true,
		},
		{
			name: "fails with expired token",
			buildToken: func(t *testing.T, _ *tokens.JWTService) string {
				t.Helper()
				claims := &tokens.CustomClaims{
					UserID: "expired-user",
					RegisteredClaims: jwt.RegisteredClaims{
						ExpiresAt: jwt.NewNumericDate(time.Now().Add(-1 * time.Hour)),
						Issuer:    validIssuer,
						IssuedAt:  jwt.NewNumericDate(time.Now().Add(-2 * time.Hour)),
					},
				}
				token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
				signed, err := token.SignedString([]byte(validSecret))
				require.NoError(t, err)
				return signed
			},
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			svc := newJWTService(t)
			tokenStr := tt.buildToken(t, svc)

			userID, err := svc.Validate(context.Background(), tokenStr)

			if tt.wantErr {
				require.Error(t, err)
				assert.Empty(t, userID)
				return
			}

			require.NoError(t, err)
			assert.Equal(t, tt.wantUserID, userID)
		})
	}
}

// TestJWTService_RoundTrip verifies that the user ID survives intact
// through a full Generate → Validate cycle.
func TestJWTService_RoundTrip(t *testing.T) {
	t.Parallel()

	svc := newJWTService(t)
	ctx := context.Background()

	originalID := "550e8400-e29b-41d4-a716-446655440000"

	token, err := svc.Generate(ctx, originalID)
	require.NoError(t, err)
	require.NotEmpty(t, token)

	recoveredID, err := svc.Validate(ctx, token)
	require.NoError(t, err)

	assert.Equal(t, originalID, recoveredID, "user ID must be preserved through round-trip")
}
